### PR TITLE
separate sync_container_context to fix problems with the same contextvar token for every context

### PR DESCRIPTION
**Pull request by lesnik512**
separate sync_container_context to fix problems with the same contextvar token for every context

### CODE REVIEW

**Comment by lesnik512** [comment]
@alexanderlazarev0 Hi) there is some problem with new container context.

The problem is that contextvar token variable is the same for all requests.

To fix this I had to separate sync container context

**Comment by alexanderlazarev0** [comment]
@lesnik512 
Do you have a minimal example to reproduce?

**Comment by lesnik512** [comment]
@alexanderlazarev0 not right now, in the evening I will make an example

**Comment by lesnik512** [comment]
@alexanderlazarev0 Error was the following:
RuntimeError
<Token used var=<ContextVar name='CONTAINER_CONTEXT' at 0x7fade72ab8d0> at 0x7fade06e8c80> has already been used once

Trying to build small reproducible example now

**Comment by alexanderlazarev0** [comment]
@lesnik512 Yes I was trying to reproduce this, but wasn't able to for now. Is this with `fastapi`?

**Comment by lesnik512** [comment]
@alexanderlazarev0 it's in kafka consumer.

There is a method which called on each message from topic:

```python
    @container_context(build_di_context("write"))
    async def process_one_message(
        self,
        message: timers_schemas.DialogUnreadMessagesTimerEvent,
        _: dict[str, typing.Any] | None = None,
    ) -> None:
         ...
```

Theres is also another version of this error:

ValueError
<Token var=<ContextVar name='CONTAINER_CONTEXT' at 0x7f3098d479c0> at 0x7f30807b7bc0> was created in a different Context

**Comment by alexanderlazarev0** [comment]
@lesnik512 Okay seems the __exit__ method of the `containter_context` is being called twice by different actors.

**Comment by lesnik512** [comment]
@alexanderlazarev0 I think, the problem is occured when decorator used: it's initialized only once and _context_token is shared between different contexts

**Comment by alexanderlazarev0** [comment]
Ah! I got it I think, its a 2 liner:
```python
# container_context class
 def __call__(self, func: typing.Callable[P, T]) -> typing.Callable[P, T]:
        if inspect.iscoroutinefunction(func):

            @wraps(func)
            async def _async_inner(*args: P.args, **kwargs: P.kwargs) -> T:
                async with self: # <- HERE
                    return await func(*args, **kwargs)  # type: ignore[no-any-return]

            return typing.cast(typing.Callable[P, T], _async_inner)

        @wraps(func)
        def _sync_inner(*args: P.args, **kwargs: P.kwargs) -> T:
            with self: # <-- HERE
                return func(*args, **kwargs)

        return _sync_inner
```

**Comment by lesnik512** [comment]
@alexanderlazarev0 seems, like this could work.

But _initial_context must be passed, I think in `__call__`:

container_context(self._initial_context)

**Comment by lesnik512** [comment]
@alexanderlazarev0 But still I have no idea how to reproduce this in tests)

**Comment by alexanderlazarev0** [comment]
@lesnik512 I think you might be able to reproduce it by calling an ``@container_context`` decorated function twice in the same call stack (i need to try just my first guess)


> @alexanderlazarev0 seems, like this could work.
> 
> But _initial_context must be passed, I think, in `__call__`:
> 
> container_context(self._initial_context)

Yes you are right this will need to be added. 

I will let you know if i can reproduce the issue.

**Comment by alexanderlazarev0** [comment]
@lesnik512 Yes got It and the suggest fix works!
Error example:
```python
from that_depends import providers
from that_depends.container import BaseContainer
from that_depends.injection import inject
from that_depends.providers.context_resources import container_context


def context_resource_creator():
    yield "interesting"


class MyContainer(BaseContainer):
    context_resource = providers.ContextResource(context_resource_creator)
@container_context()
@inject
def some_injected(depth, val = MyContainer.context_resource):
    if depth ==2:
        return val
    return some_injected(depth+1)


if __name__ == "__main__":
    some_injected(1)


```

**Comment by alexanderlazarev0** [comment]
@lesnik512 So the question is really then just one of taste:
1. Keep the current implementation, but now you need to actively annotate correctly with either ``sync_container_context`` or ``container_context``
2. Revert to the old one which is less verbose and arguably easier to use for annotations (less thought required), however it is perhaps not as intuitive to use outside annotations``with container_context()`` and ``async with container_context()``.
3. Theoretically, both solutions can coexist, but I think 1 clear way to do things is preferred.

**Comment by lesnik512** [comment]
@alexanderlazarev0 Nicely done! So I reverted to the previous version, applied fix and wrote some tests https://github.com/modern-python/that-depends/pull/94. Please, take a look

**Pull request merged**
